../services:
  postgres-db:
    image: postgres:latest
    container_name: tnews-db
    environment:
      POSTGRES_DB: tnews_DB
      POSTGRES_USER: tnews_DB
      POSTGRES_PASSWORD: postgres_tnews_DB
    networks:
      - internal_net

  mongo:
    image: mongo:latest
    container_name: mongodb_container
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: newsdb
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - internal_net

  subscription-service:
    build: ./subscription-service
    container_name: subscription-service
    depends_on:
      - postgres-db
      - aggregation-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://tnews-db:5432/tnews_DB
      SPRING_DATASOURCE_USERNAME: tnews_DB
      SPRING_DATASOURCE_PASSWORD: postgres_tnews_DB
      AGGREGATOR_SERVICE_URL: http://aggregation-service:8080/news
    networks:
      - internal_net
      - default

  aggregation-service:
    build: ./aggregation-service
    container_name: aggregation-service
    depends_on:
      - mongo
    environment:
      MONGO_USERNAME: user
      MONGO_PASSWORD: password
      MONGO_DATABASE: newsdb
      MONGO_PORT: 27017
    networks:
      - internal_net
      - default

networks:
  internal_net:
    internal: true
  default:
    driver: bridge
