server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5555/tnews_DB
    username: tnews_DB
    password: postgres_tnews_DB
    driver-class-name: org.postgresql.Driver
  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000


  jpa:
    show-sql: true

    hibernate:
      ddl-auto: update

    database-platform: org.hibernate.dialect.PostgreSQLDialect

bot:
  name: tnewsSubscriptionBot
  token: 7367963001:AAEKCLGL8Wryxq8AW5E3QlzvHHMK_Iirnjk # 8128984956:AAHhuxvs5fGkLYnXT3dhbN7uHsiIF9LiHS0

aggregator:
  service:
    url: http://localhost:8080/news