server:
  port: 8081

spring:
  datasource:
    url: ${SPRING_DATASOURCE_LOCAL_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  feign:
    client:
      config:
        default:
          connectTimeout: 5000
          readTimeout: 5000

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

bot:
  name: ${BOT_NAME:-tnewsSubscriptionBot}
  token: ${BOT_TOKEN}

aggregator:
  service:
    url: ${AGGREGATOR_SERVICE_LOCAL_URL}